### ISSUE TITLE
Copy-paste (?) problem

### ISSUE THREAD

**Issue by hernanponcedeleon** [binsec/haunted_bench#1]
I think there are a couple of inconsistencies with the benchmarks.

Except 'case2' you use `secretarray_size` instead of `publicarray_size`. While this is not an issue because both are 16, I think you assume not knowledge about the secret so for consistency it might be better to use `publicarray_size` (if it is not the case and I'm missing something, please let me know).

`case10`: it is both marked as `(secure)` and `INSECURE`. I think it is **secure**.
`case11`: it is both marked as (secure) and `INSECURE`. I think it is **secure**.
`case12`: you use `case_10_mask ` and I think it should be `case_12_mask`
`case13`: you use `case_11_load_value ` and I think it should be `case_13_load_value`

**Comment by Lesly-Ann** [comment]
Oops, you're right, copy-past mistakes ! Thanks a lot for noticing !

Fortunately, `case_10_mask` and `case_12_mask` are the same functions so it does not change the result (same for `case_11_load_value` and `case_13_load_value`). I'll just remove the duplicated functions.

For `case10` and `case11`, if I recall correctly, they are actually insecure when compiled with `gcc -O0` because the masked index is pushed on the stack---and can therefore be bypassed. I'll check that by the end of the week and add some better documentation to avoid any confusion !
