### ISSUE TITLE
Expected result of case_13

### ISSUE THREAD

**Issue by hernanponcedeleon** [binsec/haunted_bench#2]
binsec reports this benchmark as safe.
However, the program makes a call to `case_11_load_value` whose generated assembly is
```
case_11_load_value:
.LFB12:
	.cfi_startproc
	pushl	%ebp
	.cfi_def_cfa_offset 8
	.cfi_offset 5, -8
	movl	%esp, %ebp
	.cfi_def_cfa_register 5
	subl	$16, %esp
	movl	secretarray_size, %eax
	decl	%eax
	andl	8(%ebp), %eax
	movl	%eax, %edx
	movl	%edx, %eax
	movb	publicarray(%eax), %al
	movb	%al, -1(%ebp)
	movb	-1(%ebp), %al
	leave
	.cfi_restore 5
	.cfi_def_cfa 4, 4
	ret
	.cfi_endproc
.LFE12:
	.size	case_11_load_value, .-case_11_load_value
	.globl	case_11
	.type	case_11, @function
```

Noticed that the result is first written to the stack (`movb %al, -1(%ebp)`) and then read from the stack (`movb	-1(%ebp), %al`).
My understanding is that the write can by bypassed and thus the whole program should be unsafe.
Am I missing something?

**Comment by Lesly-Ann** [comment]
I had a look and I think that `case_13` is actually secure. In the following I will explain:
1. Why `case_11` is insecure (because it is very similar to `case_13`) and might help understand `case_13`,
2. Why `case_13` does not have the same vulnerability as `case_11`,
3. Why the vulnerability that you report in `case_13` is not reported as insecure by Binsec/Haunted.

I admit that this issue was a bit difficult to investigate and I might be missing something, so if you are sure that there is a vulnerability, you might be right (so feel free to tell me if you think I am wrong). If I continue working on Binsec/Haunted in the future, usability for Spectre-STL is definitely something I should improve!

I put all disassembled binaries (with asm instructions and addresses) at the end of the answer.

# Why case_11 is insecure
`case_11` is insecure because:
- At `@0804A020` the return instruction (which contains an implicit `ebp<32> := @[esp<32>,4]`) bypasses a store and takes its value from main memory. At this point, we have `ebp := @of secret`.
- At `@0804A036`, instruction `movzx eax, [ebp+ridx]` bypasses the store at `@0804A033` and takes its value from main memory. Because ebp contains a stale value, we have something like `movzx eax, [@of secret]` which loads a secret in eax.
- At `@0804A03D`, this secret is leaked to the cache.

# Why case_13  does not have the same vulnerability as case_11
Simply because the load at `@0804A036` is replaced by register assignments which cannot be bypassed.

# Why case_13 is not reported as insecure by Binsec/Haunted
You are right that the load instruction at `@0804A01D` (`mov al, [ebp-1]`) can bypass the store instruction at `@0804A01A`. The question that remains is: can it load a secret into `eax` ?

Notice that the value of `ebp` is not not free: at `@0804A002` we have `ebp := esp`, which basically sets `ebp` to an address pointing in the stack. Because secrets are not in the stack but are global variables, it seems that no secret can be stored into `eax`.

Note, that if you do not make any assumption on the value of `esp` (leave it unconstrained), Binsec/Haunted reports a violation with `initial_esp:= 0x081050b4` (which is the address of a secret data). However, this is unrealistic as the stack will not overlap with data in real executions.

However there is definitively something fishy with the countermeasure "just put the variable in a register" so thanks for reporting! I thought that the value `to_leak` in `edx` could not be a stale value but as you pointed out, I was wrong. (However it turns out that in this particular example it cannot be a secret). I guess that a more robust countermeasure would be to use an `lfence` in this case.

# Programs
## case_11
``` asm
.text:0804A001 case_11_load_value proc near  
.text:0804A001 to_leak      = byte ptr -1
.text:0804A001 idx             = dword ptr  8
.text:0804A001
.text:0804A001                 push    ebp
.text:0804A002                 mov     ebp, esp
.text:0804A004                 sub     esp, 10h
.text:0804A007                 mov     eax, secretarray_size
.text:0804A00C                 dec     eax
.text:0804A00D                 and     eax, [ebp+idx]
.text:0804A010                 mov     edx, eax
.text:0804A012                 mov     eax, edx
.text:0804A014                 mov     al, publicarray[eax]
.text:0804A01A                 mov     [ebp+to_leak], al
.text:0804A01D                 mov     al, [ebp+to_leak]
.text:0804A020                 leave  // Bypasses a store & load value from main memory: ebp := @ of secret
.text:0804A021                 retn
.text:0804A021 case_11_load_value endp


.text:0804A022                 public case_11
.text:0804A022 case_11         proc near
.text:0804A022
.text:0804A022 ridx            = byte ptr -1
.text:0804A022 idx             = dword ptr  8
.text:0804A022
.text:0804A022                 push    ebp
.text:0804A023                 mov     ebp, esp
.text:0804A025                 sub     esp, 10h
.text:0804A028                 push    [ebp+idx]
.text:0804A02B                 call    case_11_load_value
.text:0804A030                 add     esp, 4
.text:0804A033                 mov     [ebp+ridx], al  // Bypassed store
.text:0804A036                 movzx   eax, [ebp+ridx] // Bad load, takes its value from memory (load secret)
.text:0804A03A                 shl     eax, 9
.text:0804A03D                 mov     dl, publicarray2[eax] // Leak secret from eax
.text:0804A043                 mov     al, ds:temp
.text:0804A048                 and     eax, edx
.text:0804A04A                 mov     ds:temp, al
.text:0804A04F                 nop
.text:0804A050                 leave
.text:0804A051                 retn
.text:0804A051 case_11         endp
```

## case_13
``` asm
.text:0804A001 case_11_load_value proc near
.text:0804A001
.text:0804A001
.text:0804A001 to_leak      = byte ptr -1
.text:0804A001 idx             = dword ptr  8
.text:0804A001
.text:0804A001                 push    ebp
.text:0804A002                 mov     ebp, esp
.text:0804A004                 sub     esp, 10h
.text:0804A007                 mov     eax, secretarray_size
.text:0804A00C                 dec     eax
.text:0804A00D                 and     eax, [ebp+idx]
.text:0804A010                 mov     edx, eax
.text:0804A012                 mov     eax, edx
.text:0804A014                 mov     al, publicarray[eax]
.text:0804A01A                 mov     [ebp+to_leak], al
.text:0804A01D                 mov     al, [ebp+to_leak] // can [ebp-1] point to a secret ?
.text:0804A020                 leave
.text:0804A021                 retn
.text:0804A021 case_11_load_value endp

.text:0804A0B8 case_13         proc near
.text:0804A0B8
.text:0804A0B8 idx            = dword ptr  8
.text:0804A0B8
.text:0804A0B8                 push    ebp
.text:0804A0B9                 mov     ebp, esp
.text:0804A0BB                 push    [ebp+idx]
.text:0804A0BE                 call    case_11_load_value
.text:0804A0C3                 add     esp, 4
.text:0804A0C6                 mov     dl, al
.text:0804A0C8                 mov     al, dl
.text:0804A0CA                 movzx   eax, al
.text:0804A0CD                 shl     eax, 9
.text:0804A0D0                 mov     dl, publicarray2[eax] // Leak iff eax = secret
.text:0804A0D6                 mov     al, ds:temp
.text:0804A0DB                 and     eax, edx
.text:0804A0DD                 mov     ds:temp, al
.text:0804A0E2                 nop
.text:0804A0E3                 leave
.text:0804A0E4                 retn
.text:0804A0E4 case_13         endp

```

**Comment by hernanponcedeleon** [comment]
I agree that `0804A01D` cannot load a secret into `al`.

However, since `0804A01D` can be executed before than `0804A014`, it might read from initialised memory, i.e. `al` can contain any arbitrary value. Since this value is then used by `0804A0D0` as the index to access `publicarray2`, this can result in an out-of-bound access. In this scenario `// eax at 0804A0D0 can point to a secret`

It is true that a second access whose address depend on `dl` would be needed in order to use a side-channel, but AFAIK this still violates speculative-constant-time.

If I'm correct about this behaviour, one possible reason I see why binsec might miss this, is that it does not consider the initial values of the stack as symbolic.

**Comment by Lesly-Ann** [comment]
I should clarify two things:

First, Binsec does consider initial values in the stack as symbolic. However, they are public by default. I agree that if you use a different assumption a consider that initial stack at address `[ebp+to_leak]` can be secret, then at `@0804A01D`, `al := secret` and there is a vulnerability at `@0804A0D0`.

Second, we only report a load as insecure if its address is secret. At `@0804A0D0`, `eax` is not secret so the load is not reported as insecure. However, it is true that `eax` can be an address that points to a secret. In this case `dl := secret` but we do not consider this as a violation because `dl` does not leak to the microarchitecture at this point. The program would be reported as insecure only if `dl` was used in a control flow instruction or as a memory index.

I think that the misunderstanding comes from my second point. From what I understand, we do not use the same definition of speculative constant-time.

**Comment by hernanponcedeleon** [comment]
Yes, now that you explain what binsec would report as insecure, I realise that I was considering a different threat model were I consider a program unsafe as soon as some load access the secret.

As a summary, do we agree that "assuming the processor supports store-to-load forwarding speculation, it is possible that some load *access the address where the secret is stored* (here `@0804A0D0`), but since SCT considers a program insecure if the address of a load *is the secret*, binsec correctly reports it as safe (wrt SCT)"?

**Comment by Lesly-Ann** [comment]
Yes, we agree :+1:

**Comment by hernanponcedeleon** [comment]
Great! Thanks a lot for the clarification
